### ISSUE TITLE
Version openmodelica

### ISSUE THREAD

**Issue by Yahiaassam** [Virtual-FCS/VirtualFCS#34]
Salut, je suis yahia, je travaille sur openmodelica et j’ai besoin du FCS virtuel, donc j’aimerais savoir dans quelle version cette bibliothèque fonctionne en openmodelica ? en fait j’utilise la version 1.18;
Merci pour vos besoins
bonne journée.

**Comment by kvid** [comment]
OM 1.14 should work. See more details in #1.

**Comment by Yahiaassam** [comment]
thank you for your reply
So for version 1.18 it poses problems?

**Comment by kvid** [comment]
OM 1.14 is specified as a [system requirement](https://github.com/Virtual-FCS/VirtualFCS#system-requirements-and-installation) and issue #1 contains descriptions of problems with recent OM versions, but I've not investigated this personally. I cannot guarantee that it is impossible to find some parts of the current VirtualFCS version that might work together with OM 1.18, but I don't expect it to work.

**Comment by Yahiaassam** [comment]
Thank you.
