### ISSUE TITLE
Erreur lors de la vérification des modèles

### ISSUE THREAD

**Issue by Gaultier70** [Virtual-FCS/VirtualFCS#36]
Bonjour,

Il m'est indiqué "Traduction erreur" lorsque je lance la vérification des modèles, hormis pour la partie électrochimique. Il y a t'il une manipulation particulière à faire ?

De plus, lorsque je lance la simulation, aucun modèle présent dans le package ne marche. Il m'est indiqué "Traduction erreur" et "Symbolique erreur". 

Comment puis-je faire pour résoudre ces problèmes ? 

Merci d'avance et bonne journée

**Comment by mikegerhardt** [comment]
Hello,

Thanks for giving VirtualFCS a try! I have a couple questions to try to help resolve the problem.

Which version of OpenModelica are you using? What operating system? I have seen "Translation errors" when using the latest version of OpenModelica (1.19) with models containing fuelCellStack or fuelCellSystem classes. This error is related to updates in the fluid models, and we're working on solutions. In the meantime, you can try downgrading to version 1.14 or 1.14.1.

Does the CycleBatteryCell example work? We've gotten it to work on OM 1.19 with Windows 10.

Please feel free to follow up with additional screenshots or copy-pasted error messages. The more information the better!

**Comment by kvid** [comment]
[VirtualFCS v2.0.0](https://github.com/Virtual-FCS/VirtualFCS/releases/tag/v2.0.0), supporting OM v1.20 for Windows, has now been released. Please try to see if this also solves your use cases, @Gaultier70.
